-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.profiles (
  id uuid NOT NULL,
  full_name text NOT NULL,
  email text NOT NULL,
  phone text NOT NULL,
  profile_picture text,
  emergency_contact_name text,
  emergency_contact_phone text,
  last_login_at timestamp with time zone,
  phone_verified boolean DEFAULT false,
  account_source text DEFAULT 'email_password'::text CHECK (account_source = ANY (ARRAY['email_password'::text, 'otp'::text, 'google'::text])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  national_id text,
  is_admin boolean NOT NULL DEFAULT false,
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.trips (
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  driver_id uuid NOT NULL,
  route_template_id uuid,
  origin text NOT NULL,
  destination text NOT NULL,
  origin_region text,
  destination_region text,
  pickup_point text,
  dropoff_point text,
  departure_time timestamp with time zone NOT NULL,
  estimated_arrival_time timestamp with time zone,
  price_per_seat numeric NOT NULL CHECK (price_per_seat > 0::numeric),
  total_seats integer NOT NULL CHECK (total_seats > 0),
  available_seats integer NOT NULL CHECK (available_seats >= 0),
  vehicle_make text,
  vehicle_model text,
  vehicle_plate text,
  vehicle_color text,
  cancellation_reason text,
  cancelled_at timestamp with time zone,
  notes text,
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  status text NOT NULL DEFAULT 'scheduled'::text CHECK (status = ANY (ARRAY['scheduled'::text, 'ongoing'::text, 'completed'::text, 'cancelled'::text, 'expired'::text])),
  CONSTRAINT trips_pkey PRIMARY KEY (id),
  CONSTRAINT trips_driver_id_fkey FOREIGN KEY (driver_id) REFERENCES public.profiles(id),
  CONSTRAINT trips_route_template_id_fkey FOREIGN KEY (route_template_id) REFERENCES public.route_templates(id)
);
CREATE TABLE public.bookings (
  booking_reference text NOT NULL UNIQUE,
  trip_id uuid NOT NULL,
  passenger_id uuid NOT NULL,
  seats_booked integer NOT NULL CHECK (seats_booked > 0),
  price_per_seat_snapshot numeric NOT NULL,
  total_price numeric NOT NULL,
  cancelled_at timestamp with time zone,
  cancelled_by uuid,
  cancellation_reason text,
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  status text NOT NULL DEFAULT 'confirmed'::text CHECK (status = ANY (ARRAY['pending'::text, 'confirmed'::text, 'cancelled'::text, 'completed'::text, 'no_show'::text])),
  refund_status text NOT NULL DEFAULT 'not_applicable'::text CHECK (refund_status = ANY (ARRAY['not_applicable'::text, 'pending'::text, 'processed'::text, 'failed'::text])),
  pickup_point text,
  dropoff_point text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT bookings_pkey PRIMARY KEY (id),
  CONSTRAINT bookings_trip_id_fkey FOREIGN KEY (trip_id) REFERENCES public.trips(id),
  CONSTRAINT bookings_passenger_id_fkey FOREIGN KEY (passenger_id) REFERENCES public.profiles(id),
  CONSTRAINT bookings_cancelled_by_fkey FOREIGN KEY (cancelled_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.route_templates (
  origin text NOT NULL,
  destination text NOT NULL,
  origin_region text,
  destination_region text,
  typical_duration_minutes integer,
  typical_price_min numeric,
  typical_price_max numeric,
  created_by uuid,
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT route_templates_pkey PRIMARY KEY (id),
  CONSTRAINT route_templates_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.notifications (
  user_id uuid NOT NULL,
  type text NOT NULL CHECK (type = ANY (ARRAY['booking_created'::text, 'booking_confirmed'::text, 'booking_cancelled'::text, 'trip_cancelled'::text, 'trip_reminder'::text, 'trip_completed'::text, 'kyc_submitted'::text, 'kyc_approved'::text, 'kyc_rejected'::text, 'verification_required'::text, 'account_suspended'::text, 'account_reactivated'::text, 'rating_received'::text, 'dispute_update'::text, 'admin_announcement'::text])),
  title text NOT NULL,
  body text,
  data jsonb,
  read_at timestamp with time zone,
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  is_read boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT notifications_pkey PRIMARY KEY (id),
  CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.ratings (
  booking_id uuid NOT NULL,
  trip_id uuid NOT NULL,
  rater_id uuid NOT NULL,
  ratee_id uuid NOT NULL,
  rating_type text NOT NULL CHECK (rating_type = ANY (ARRAY['passenger_to_driver'::text, 'driver_to_passenger'::text])),
  rating integer NOT NULL CHECK (rating >= 1 AND rating <= 5),
  comment text,
  removed_by_admin uuid,
  removed_at timestamp with time zone,
  removal_reason text,
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  flagged_for_review boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ratings_pkey PRIMARY KEY (id),
  CONSTRAINT ratings_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id),
  CONSTRAINT ratings_trip_id_fkey FOREIGN KEY (trip_id) REFERENCES public.trips(id),
  CONSTRAINT ratings_rater_id_fkey FOREIGN KEY (rater_id) REFERENCES public.profiles(id),
  CONSTRAINT ratings_ratee_id_fkey FOREIGN KEY (ratee_id) REFERENCES public.profiles(id),
  CONSTRAINT ratings_removed_by_admin_fkey FOREIGN KEY (removed_by_admin) REFERENCES public.profiles(id)
);
CREATE TABLE public.reports (
  reporter_id uuid NOT NULL,
  reported_user_id uuid,
  trip_id uuid,
  booking_id uuid,
  category text NOT NULL CHECK (category = ANY (ARRAY['safety'::text, 'harassment'::text, 'no_show'::text, 'payment_dispute'::text, 'fake_profile'::text, 'vehicle_mismatch'::text, 'reckless_driving'::text, 'other'::text])),
  description text NOT NULL,
  assigned_to uuid,
  resolved_by uuid,
  resolution_notes text,
  resolved_at timestamp with time zone,
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  status text NOT NULL DEFAULT 'open'::text CHECK (status = ANY (ARRAY['open'::text, 'under_review'::text, 'resolved'::text, 'dismissed'::text])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT reports_pkey PRIMARY KEY (id),
  CONSTRAINT reports_reporter_id_fkey FOREIGN KEY (reporter_id) REFERENCES public.profiles(id),
  CONSTRAINT reports_reported_user_id_fkey FOREIGN KEY (reported_user_id) REFERENCES public.profiles(id),
  CONSTRAINT reports_trip_id_fkey FOREIGN KEY (trip_id) REFERENCES public.trips(id),
  CONSTRAINT reports_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id),
  CONSTRAINT reports_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES public.profiles(id),
  CONSTRAINT reports_resolved_by_fkey FOREIGN KEY (resolved_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.audit_logs (
  admin_id uuid,
  user_id uuid,
  action text NOT NULL,
  table_name text NOT NULL,
  record_id uuid,
  old_value jsonb,
  new_value jsonb,
  ip_address text,
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT audit_logs_pkey PRIMARY KEY (id),
  CONSTRAINT audit_logs_admin_id_fkey FOREIGN KEY (admin_id) REFERENCES public.profiles(id),
  CONSTRAINT audit_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.driver_profiles (
  profile_id uuid NOT NULL,
  vehicle_make text,
  vehicle_model text,
  vehicle_plate text,
  vehicle_seats integer,
  vehicle_year integer,
  vehicle_color text,
  licence_number text,
  licence_class text,
  licence_expiry date,
  kyc_documents jsonb,
  kyc_submitted_at timestamp with time zone,
  kyc_approved_at timestamp with time zone,
  kyc_approved_by uuid,
  kyc_rejection_reason text,
  suspension_reason text,
  verification_status text NOT NULL DEFAULT 'pending'::text,
  kyc_attempts integer DEFAULT 0,
  trust_level integer DEFAULT 1,
  max_seats_per_trip integer DEFAULT 2,
  max_active_trips integer DEFAULT 1,
  payout_delay_hours integer DEFAULT 48,
  trips_completed integer DEFAULT 0,
  dispute_count integer DEFAULT 0,
  flagged_for_review boolean DEFAULT false,
  account_status text NOT NULL DEFAULT 'active'::text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT driver_profiles_pkey PRIMARY KEY (profile_id),
  CONSTRAINT driver_profiles_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.profiles(id),
  CONSTRAINT driver_profiles_kyc_approved_by_fkey FOREIGN KEY (kyc_approved_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.passenger_profiles (
  profile_id uuid NOT NULL,
  suspension_reason text,
  verification_status text NOT NULL DEFAULT 'active'::text,
  trust_level integer DEFAULT 1,
  trips_completed integer DEFAULT 0,
  dispute_count integer DEFAULT 0,
  flagged_for_review boolean DEFAULT false,
  account_status text NOT NULL DEFAULT 'active'::text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT passenger_profiles_pkey PRIMARY KEY (profile_id),
  CONSTRAINT passenger_profiles_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.active_sessions (
  profile_id uuid NOT NULL,
  role text NOT NULL CHECK (role = ANY (ARRAY['driver'::text, 'passenger'::text, 'admin'::text])),
  session_id uuid NOT NULL,
  device_label text,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT active_sessions_pkey PRIMARY KEY (profile_id, role),
  CONSTRAINT active_sessions_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.profiles(id)
);